### ISSUE TITLE
ROS tf python3 incompatibility 

### ISSUE THREAD

**Issue by jacknlliu** [jacknlliu/gps#1]
import tf from python3 will not work. This holds the python3 support back.
```sh
$ python3

>>> from tf import TransformListener
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tf/__init__.py", line 28, in <module>
    from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException
  File "/home/ros/data/tf2_ros/catkin_ws/devel/lib/python2.7/dist-packages/tf2_ros/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 38, in <module>
  File "/home/ros/data/tf2_ros/catkin_ws/devel/lib/python2.7/dist-packages/tf2_py/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 38, in <module>
ImportError: dynamic module does not define module export function (PyInit__tf2)
```

## Reference
- https://github.com/ros/geometry2/issues/259
- https://stackoverflow.com/questions/24226001/importerror-dynamic-module-does-not-define-init-function-initfizzbuzz

**Comment by zishanahmed08** [comment]
@jacknlliu Hi jack,I am experiencing the same issue. Wer u able to solve this?
